# Generated by Django 5.2.4 on 2025-07-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='sender_name',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='greeting',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
