# Generated by Django 5.2.4 on 2025-07-21 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_sender_name_response_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='greeting',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Anonymous', max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hello.message')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
